name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

jobs:
  update_release_draft:
    name: Run
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
