name: Scientific validation
on:
  schedule:
    - cron: "17 3 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  release-tests:
    name: Scientific validation
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-tests.yml@ace7363a2a8e036e5efc6717be67f1eda29a120e # v2.4.2
    with:
      runs-on: ubuntu-24.04
      sessions: '["release-tests"]'
      use-sccache-gha: false
    permissions:
      contents: read
