name: Templating
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/templating.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  render-template:
    name: Render template
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: create-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: munich-quantum-toolkit/templates@58aa931467691cea6d910016e1c75ab83780bc54 # v1.2.0
        with:
          token: ${{ steps.create-token.outputs.token }}
          name: YAQS
          organization: ${{ github.repository_owner }}
          project-type: pure-python
          repository: ${{ github.event.repository.name }}
